import argparse
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional, Union

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

# Configure structured logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("inference_engine")

PROMPT_TEMPLATE = (
    "<|instruction|>\nAnalyze the Java code and identify ALL security vulnerabilities. Return structured JSON only.\n\n"
    "<|input|>\n{raw_code}\n\n"
    "<|response|>\n"
)


class VulnerabilityInferenceEngine:
    """
    Manages loading a base model in 4-bit precision, overlays a PEFT adapter,
    and handles deterministic vulnerability analysis of Java files.
    """
    def __init__(
        self,
        model_id: str,
        adapter_path: Optional[Union[str, Path]] = None,
        load_in_4bit: bool = True
    ) -> None:
        """
        Initializes the inference engine by loading the model and tokenizer.

        Args:
            model_id: HuggingFace model hub ID or local path to base model.
            adapter_path: Local path to trained PEFT adapter checkpoints (optional).
            load_in_4bit: Whether to load the base model in 4-bit precision (requires CUDA).
        """
        self.model_id = model_id
        self.adapter_path = adapter_path
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

        # Check if model_id is a local directory containing a merged model
        is_local = Path(model_id).is_dir()

        try:
            logger.info(f"Loading tokenizer for model: {model_id} (local: {is_local})")
            self.tokenizer = AutoTokenizer.from_pretrained(
                model_id,
                trust_remote_code=True,
                local_files_only=is_local
            )
            if self.tokenizer.pad_token_id is None:
                self.tokenizer.pad_token = self.tokenizer.eos_token
                if self.tokenizer.pad_token_id is None:
                    self.tokenizer.pad_token_id = self.tokenizer.eos_token_id

            # Determine quantization and device map
            bnb_config = None
            device_map = None

            if load_in_4bit and torch.cuda.is_available():
                compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
                logger.info(f"Configuring 4-bit BitsAndBytes quantization. Compute dtype: {compute_dtype}")
                bnb_config = BitsAndBytesConfig(
                    load_in_4bit=True,
                    bnb_4bit_quant_type="nf4",
                    bnb_4bit_use_double_quant=True,
                    bnb_4bit_compute_dtype=compute_dtype
                )
                device_map = "auto"
            else:
                logger.warning("BitsAndBytes 4-bit is disabled or CUDA is unavailable. Loading base model in full precision.")

            logger.info(f"Loading base/merged model: {model_id} (local: {is_local})")
            base_model = AutoModelForCausalLM.from_pretrained(
                model_id,
                quantization_config=bnb_config,
                device_map=device_map,
                trust_remote_code=True,
                local_files_only=is_local
            )

            # Apply PEFT adapter if provided
            if self.adapter_path:
                logger.info(f"Overlaying PEFT adapter from path: {self.adapter_path}")
                self.model = PeftModel.from_pretrained(base_model, str(self.adapter_path))
            else:
                if is_local:
                    logger.info("No adapter path specified. Using local model directly (assumed merged/standalone).")
                else:
                    logger.warning("No PEFT adapter specified. Running raw base model.")
                self.model = base_model

            self.model.eval()
            logger.info("Inference engine model configuration and setup completed successfully.")

        except Exception as err:
            logger.error(f"Failed to initialize VulnerabilityInferenceEngine: {err}", exc_info=True)
            raise

    def analyze_file_content(self, raw_code: str, max_new_tokens: int = 1024) -> Dict[str, Any]:
        """
        Wraps raw Java code into the specialized token prompt layout, generates
        a vulnerability report using deterministic greedy search, and parses JSON output.

        Args:
            raw_code: The raw Java source code content string.
            max_new_tokens: Maximum tokens allowed to be generated by the model.

        Returns:
            A parsed JSON dictionary of vulnerabilities or an error dictionary.
        """
        try:
            # 1. Wrap raw code in Prompt structure
            prompt = PROMPT_TEMPLATE.format(raw_code=raw_code)
            
            # Tokenize input prompt
            inputs = self.tokenizer(prompt, return_tensors="pt")
            input_ids = inputs["input_ids"].to(self.model.device)
            attention_mask = inputs["attention_mask"].to(self.model.device)

            # 2. Run deterministic generation (do_sample=False)
            with torch.no_grad():
                outputs = self.model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    max_new_tokens=max_new_tokens,
                    do_sample=False,  # Greedy decoding for determinism
                    eos_token_id=self.tokenizer.eos_token_id,
                    pad_token_id=self.tokenizer.pad_token_id
                )

            # 3. Extract and decode ONLY the generated tokens (excluding the prompt tokens)
            generated_tokens = outputs[0][len(input_ids[0]):]
            generated_response = self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()

            # Ensure we stop if the tokenizer EOS token is in string representation
            eos_token_str = self.tokenizer.eos_token
            if eos_token_str and eos_token_str in generated_response:
                generated_response = generated_response.split(eos_token_str)[0].strip()

            # 4. Safely parse response using the native json library
            return self._parse_json_safely(generated_response)

        except Exception as err:
            logger.error(f"Inference execution failed on code block: {err}", exc_info=True)
            return {
                "vulnerabilities": [],
                "error": f"Inference execution failed: {str(err)}"
            }

    def _parse_json_safely(self, text: str) -> Dict[str, Any]:
        """
        Cleans markdown wrappers and parses JSON blocks from raw text responses.
        """
        cleaned_text = text.strip()

        # Remove markdown code blocks if the model wrapped the JSON output
        if cleaned_text.startswith("```"):
            # Skip past '```json' or '```'
            first_newline = cleaned_text.find("\n")
            if first_newline != -1:
                cleaned_text = cleaned_text[first_newline:].strip()
            if cleaned_text.endswith("```"):
                cleaned_text = cleaned_text[:-3].strip()

        # Find first curly brace and last curly brace to isolate the JSON object
        start_brace = cleaned_text.find("{")
        end_brace = cleaned_text.rfind("}")

        if start_brace != -1 and end_brace != -1 and end_brace > start_brace:
            json_candidate = cleaned_text[start_brace:end_brace + 1]
        else:
            json_candidate = cleaned_text

        try:
            parsed_data: Dict[str, Any] = json.loads(json_candidate)
            # Standardize returned output layout
            if "vulnerabilities" not in parsed_data:
                parsed_data = {"vulnerabilities": [], "raw_output": parsed_data}
            return parsed_data
        except json.JSONDecodeError as decode_err:
            logger.error(f"Failed to decode response as JSON. Raw output: {text}. Error: {decode_err}")
            return {
                "vulnerabilities": [],
                "error": f"Invalid JSON format: {str(decode_err)}",
                "raw_response": text
            }


def format_report_as_markdown(report: Dict[str, Any]) -> str:
    """
    Converts a structured vulnerability report dictionary into a user-readable Markdown string.
    """
    if "error" in report:
        return (
            f"# Vulnerability Scan Report\n\n"
            f"❌ **Inference Error Encountered**\n\n"
            f"> {report['error']}\n\n"
            f"### Raw Response\n"
            f"```text\n{report.get('raw_response', 'No raw response available.')}\n```\n"
        )
        
    vulns = report.get("vulnerabilities", [])
    if not vulns:
        return (
            f"# Vulnerability Scan Report\n\n"
            f"✅ **No vulnerabilities detected!**\n\n"
            f"The scan completed successfully and identified no security issues in the provided code.\n"
        )
        
    md = []
    md.append("# Vulnerability Scan Report\n")
    md.append(f"### 📊 Summary: **{len(vulns)}** vulnerability/vulnerabilities detected.\n")
    md.append("---")
    
    for idx, vuln in enumerate(vulns, 1):
        cwe_id = vuln.get("cwe_id", "N/A")
        cwe_name = vuln.get("cwe_name", "Unknown CWE")
        severity = vuln.get("severity", "medium").upper()
        confidence = vuln.get("confidence", "N/A")
        description = vuln.get("description", "No description provided.")
        impact = vuln.get("impact", "No impact details provided.")
        recommendation = vuln.get("recommendation", "No recommendation provided.")
        
        # Determine a color/emoji for severity
        sev_emoji = "⚪"
        if severity == "CRITICAL":
            sev_emoji = "🔴"
        elif severity == "HIGH":
            sev_emoji = "fiber_manual_record"
            sev_emoji = "🔴"
        elif severity == "MEDIUM":
            sev_emoji = "🟡"
        elif severity == "LOW":
            sev_emoji = "🔵"
            
        md.append(f"\n## {idx}. {sev_emoji} {cwe_name} ({cwe_id})")
        md.append(f"- **Severity**: `{severity}`")
        if confidence != "N/A":
            md.append(f"- **Confidence**: `{confidence}`")
        
        location = vuln.get("location", {})
        if location:
            loc_str = []
            if "class" in location:
                loc_str.append(f"Class: `{location['class']}`")
            if "method" in location:
                loc_str.append(f"Method: `{location['method']}`")
            if "line" in location:
                loc_str.append(f"Line: `{location['line']}`")
            if loc_str:
                md.append(f"- **Location**: {', '.join(loc_str)}")
                
        md.append(f"\n### 📝 Description\n{description}")
        if impact and impact != "No impact details provided.":
            md.append(f"\n### ⚠️ Impact\n{impact}")
        md.append(f"\n### 💡 Recommendation\n{recommendation}")
        
        # If there is a fixed_code or remediation block, show it
        if "fixed_code" in vuln:
            md.append(f"\n#### Suggested Remediation Code:\n```java\n{vuln['fixed_code']}\n```")
        elif "fixed_code" in report:  # fallback if model returned it at top level
            md.append(f"\n#### Suggested Remediation Code:\n```java\n{report['fixed_code']}\n```")
            
        md.append("\n---")
        
    return "\n".join(md)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Inference Engine Verification")
    parser.add_argument("--model_id", type=str, required=True, help="Base model identifier or local merged model directory")
    parser.add_argument("--adapter_path", type=str, default=None, help="PEFT adapter weights directory")
    parser.add_argument("--snippet_path", type=str, required=True, help="Path to Java file snippet to scan")
    parser.add_argument("--no_quant", action="store_true", help="Disable 4-bit quantization")
    parser.add_argument("--format", type=str, choices=["json", "markdown"], default="markdown", help="Output format (default: markdown)")
    args = parser.parse_args()

    snippet_file = Path(args.snippet_path)
    if not snippet_file.exists():
        logger.error(f"Target snippet file not found: {snippet_file}")
        exit(1)

    try:
        with open(snippet_file, "r", encoding="utf-8", errors="ignore") as f:
            code_content = f.read()

        engine = VulnerabilityInferenceEngine(
            model_id=args.model_id,
            adapter_path=args.adapter_path,
            load_in_4bit=not args.no_quant
        )

        logger.info("Executing deterministic analysis on file contents...")
        report = engine.analyze_file_content(code_content)

        if args.format == "markdown":
            formatted_report = format_report_as_markdown(report)
            print(formatted_report)
        else:
            print("\n" + "=" * 50)
            print("INFERENCE VULNERABILITY REPORT (JSON):")
            print("=" * 50)
            print(json.dumps(report, indent=4))
            print("=" * 50 + "\n")

    except Exception as e:
        logger.error(f"Verification run failed: {e}", exc_info=True)
